name: Winget Release

on:
  release:
    types: [published]

jobs:
  winget:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: PiersSinclair.CardPool
          installers-regex: 'cpool-win-(x64|arm64)\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
